apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: avideo
  name: avideo
  namespace: avideo
spec:
  ports:
    - name: "2053"
      port: 2053
      targetPort: 2053
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: avideo
status:
  loadBalancer: {}
