name: k8s-avideo
services:
  avideo:
    build:
      context: /home/ubuntu/k8s-avideo
      dockerfile: Dockerfile
      args:
        CONTACT_EMAIL: ""
        CREATE_TLS_CERTIFICATE: ""
        DB_MYSQL_HOST: database
        DB_MYSQL_NAME: avideo
        DB_MYSQL_PASSWORD: avideo
        DB_MYSQL_PORT: "3306"
        DB_MYSQL_USER: avideo
        ENABLE_PHPMYADMIN: "yes"
        HTTP_PORT: "80"
        HTTPS_PORT: "443"
        MAIN_LANGUAGE: ""
        PHPMYADMIN_ENCODER_PORT: "8082"
        PHPMYADMIN_PORT: "8081"
        SERVER_NAME: localhost
        SOCKET_PORT: "2053"
        SYSTEM_ADMIN_PASSWORD: ""
        TLS_CERTIFICATE_FILE: ""
        TLS_CERTIFICATE_KEY: ""
        WEBSITE_TITLE: ""
    depends_on:
      database:
        condition: service_healthy
      database_encoder:
        condition: service_healthy
    environment:
      CONTACT_EMAIL: admin@localhost
      CREATE_TLS_CERTIFICATE: "yes"
      DB_MYSQL_HOST: database
      DB_MYSQL_NAME: avideo
      DB_MYSQL_PASSWORD: avideo
      DB_MYSQL_PORT: "3306"
      DB_MYSQL_USER: avideo
      ENABLE_PHPMYADMIN: "yes"
      HTTP_PORT: "80"
      HTTPS_PORT: "80"
      MAIN_LANGUAGE: en_US
      NGINX_HTTP_PORT: "8080"
      NGINX_HTTPS_PORT: "8443"
      NGINX_RTMP_PORT: "1935"
      PHPMYADMIN_ENCODER_PORT: "8082"
      PHPMYADMIN_PORT: "8081"
      SERVER_NAME: localhost
      SOCKET_PORT: "2053"
      SYSTEM_ADMIN_PASSWORD: password
      TLS_CERTIFICATE_FILE: /etc/apache2/ssl/localhost.crt
      TLS_CERTIFICATE_KEY: /etc/apache2/ssl/localhost.key
      WEBSITE_TITLE: AVideo
    healthcheck:
      test:
      - CMD-SHELL
      - curl --silent --fail http://localhost || exit 1
      timeout: 10s
      interval: 30s
      retries: 3
    networks:
      app_net: null
    ports:
    - mode: ingress
      target: 2053
      published: "2053"
      protocol: tcp
    - mode: ingress
      target: 80
      published: "80"
      protocol: tcp
    - mode: ingress
      target: 443
      published: "443"
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /home/ubuntu/k8s-avideo/.compose/tmp
      target: /var/www/tmp
      bind:
        create_host_path: true
    - type: bind
      source: /home/ubuntu/k8s-avideo/.compose/HLS
      target: /HLS
      bind:
        create_host_path: true
    - type: bind
      source: /home/ubuntu/k8s-avideo
      target: /var/www/html/AVideo
      bind:
        create_host_path: true
    - type: bind
      source: /home/ubuntu/k8s-avideo/.compose/videos
      target: /var/www/html/AVideo/videos
      bind:
        create_host_path: true
    - type: bind
      source: /home/ubuntu/k8s-avideo/.compose/encoder
      target: /var/www/html/AVideo/Encoder
      bind:
        create_host_path: true
    - type: bind
      source: /home/ubuntu/k8s-avideo/.compose/letsencrypt
      target: /etc/letsencrypt
      bind:
        create_host_path: true
  database:
    environment:
      MYSQL_DATABASE: avideo
      MYSQL_INITDB_SKIP_TZINFO: "1"
      MYSQL_PASSWORD: avideo
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: avideo
    healthcheck:
      test:
      - CMD-SHELL
      - mysqladmin ping -h localhost -u root -pexample
      timeout: 10s
      interval: 30s
      retries: 3
    image: mariadb:latest
    networks:
      app_net: null
    restart: unless-stopped
    volumes:
    - type: bind
      source: /home/ubuntu/k8s-avideo/.compose/db
      target: /var/lib/mysql
      bind:
        create_host_path: true
  database_encoder:
    environment:
      MYSQL_DATABASE: avideo_encoder
      MYSQL_INITDB_SKIP_TZINFO: "1"
      MYSQL_PASSWORD: avideo
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: avideo
    healthcheck:
      test:
      - CMD-SHELL
      - mysqladmin ping -h localhost -u root -pexample
      timeout: 10s
      interval: 30s
      retries: 3
    image: mariadb:latest
    networks:
      app_net: null
    restart: unless-stopped
    volumes:
    - type: bind
      source: /home/ubuntu/k8s-avideo/.compose/db_encoder
      target: /var/lib/mysql
      bind:
        create_host_path: true
  live:
    build:
      context: /home/ubuntu/k8s-avideo
      dockerfile: Dockerfile.live
    depends_on:
      avideo:
        condition: service_healthy
      database:
        condition: service_healthy
    environment:
      CREATE_TLS_CERTIFICATE: "yes"
      DB_MYSQL_HOST: database
      DB_MYSQL_NAME: avideo
      DB_MYSQL_PASSWORD: avideo
      DB_MYSQL_PORT: "3306"
      DB_MYSQL_USER: avideo
      ENABLE_PHPMYADMIN: "yes"
      HTTP_PORT: "80"
      HTTPS_PORT: "443"
      NGINX_HTTP_PORT: "8080"
      NGINX_HTTPS_PORT: "8443"
      NGINX_RTMP_PORT: "1935"
      PHPMYADMIN_ENCODER_PORT: "8082"
      PHPMYADMIN_PORT: "8081"
      SERVER_NAME: localhost
      SOCKET_PORT: "2053"
      TLS_CERTIFICATE_FILE: /etc/apache2/ssl/localhost.crt
      TLS_CERTIFICATE_KEY: /etc/apache2/ssl/localhost.key
    healthcheck:
      test:
      - CMD-SHELL
      - curl --silent --fail http://localhost:8080 || exit 1
      timeout: 10s
      interval: 30s
      retries: 3
    networks:
      app_net: null
    ports:
    - mode: ingress
      target: 1935
      published: "1935"
      protocol: tcp
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
    - mode: ingress
      target: 8443
      published: "8443"
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /home/ubuntu/k8s-avideo/.compose/tmp
      target: /var/www/tmp
      bind:
        create_host_path: true
    - type: bind
      source: /home/ubuntu/k8s-avideo/.compose/HLS
      target: /HLS
      bind:
        create_host_path: true
    - type: bind
      source: /home/ubuntu/k8s-avideo/.compose/letsencrypt
      target: /etc/letsencrypt
      bind:
        create_host_path: true
  phpmyadmin:
    depends_on:
      database:
        condition: service_started
    environment:
      HIDE_PHP_VERSION: "true"
      PMA_CONTROLPASS: avideo
      PMA_CONTROLUSER: avideo
      PMA_HOST: database
      PMA_PORT: "3306"
    image: phpmyadmin/phpmyadmin
    networks:
      app_net: null
    ports:
    - mode: ingress
      target: 80
      published: "8081"
      protocol: tcp
    restart: unless-stopped
  phpmyadmin_encoder:
    depends_on:
      database_encoder:
        condition: service_started
    environment:
      HIDE_PHP_VERSION: "true"
      PMA_CONTROLPASS: avideo
      PMA_CONTROLUSER: avideo
      PMA_HOST: database_encoder
      PMA_PORT: "3306"
    image: phpmyadmin/phpmyadmin
    networks:
      app_net: null
    ports:
    - mode: ingress
      target: 80
      published: "8082"
      protocol: tcp
    restart: unless-stopped
networks:
  app_net:
    name: k8s-avideo_app_net
    driver: bridge
