apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: avideo-claim1
  name: avideo-claim1
  namespace: avideo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
status: {}
