apiVersion: v1
kind: PersistentVolume
metadata:
  name: avideo-pv1
  labels:
    type: local
  namespace: avideo
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  claimRef:
    name: avideo-claim1
    namespace: avideo
  accessModes:
  - ReadWriteMany
  nfs:
    server: "10.0.0.111"
    path: "/www"
