apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: live
  name: live
  namespace: avideo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: live
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-avideo-app-net: "true"
        io.kompose.service: live
    spec:
      hostAliases:
      - ip: "10.254.4.254"
        hostnames:
        - "database"
      - ip: "10.254.53.99"
        hostnames:
        - "database-encoder"
      containers:
        - env:
            - name: CREATE_TLS_CERTIFICATE
              value: "yes"
            - name: DB_MYSQL_HOST
              value: "database"
            - name: DB_MYSQL_NAME
              value: avideo
            - name: DB_MYSQL_PASSWORD
              value: avideo
            - name: DB_MYSQL_PORT
              value: "3306"
            - name: DB_MYSQL_USER
              value: avideo
            - name: ENABLE_PHPMYADMIN
              value: "yes"
            - name: HTTPS_PORT
              value: "443"
            - name: HTTP_PORT
              value: "80"
            - name: NGINX_HTTPS_PORT
              value: "8443"
            - name: NGINX_HTTP_PORT
              value: "8080"
            - name: NGINX_RTMP_PORT
              value: "1935"
            - name: PHPMYADMIN_ENCODER_PORT
              value: "8082"
            - name: PHPMYADMIN_PORT
              value: "8081"
            - name: SERVER_NAME
              value: localhost
            - name: SOCKET_PORT
              value: "2053"
            - name: TLS_CERTIFICATE_FILE
              value: /etc/apache2/ssl/localhost.crt
            - name: TLS_CERTIFICATE_KEY
              value: /etc/apache2/ssl/localhost.key
          image: youcefouarab/avideo-live:latest
          securityContext:
            privileged: true
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 20
            periodSeconds: 30
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: live
          ports:
            - containerPort: 1935
            - containerPort: 8080
            - containerPort: 8443
          resources: {}
          volumeMounts:
            - mountPath: /var/www/tmp
              name: live-claim0
            - mountPath: /HLS
              name: live-claim1
              subPath: AVideo/HLS
            - mountPath: /etc/letsencrypt
              name: live-claim2
              subPath: AVideo/letsencrypt
      restartPolicy: Always
      volumes:
        - name: live-claim0
          emptyDir: {}
        - name: live-claim1
          persistentVolumeClaim:
            claimName: live-claim1
        - name: live-claim2
          persistentVolumeClaim:
            claimName: live-claim2
status: {}
