apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database-claim0
  name: database-claim0
  namespace: avideo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
status: {}
