apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: live-claim2
  namespace: avideo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-sc-cinderplugin
