apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: phpmyadmin
  name: phpmyadmin
  namespace: avideo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: phpmyadmin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-avideo-app-net: "true"
        io.kompose.service: phpmyadmin
    spec:
      hostAliases:
      - ip: "10.254.4.254"
        hostnames:
        - "database"
      containers:
        - env:
            - name: HIDE_PHP_VERSION
              value: "true"
            - name: PMA_CONTROLPASS
              value: avideo
            - name: PMA_CONTROLUSER
              value: avideo
            - name: PMA_HOST
              value: "database"
            - name: PMA_PORT
              value: "3306"
          image: phpmyadmin/phpmyadmin
          name: phpmyadmin
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
