apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: live-claim2
  name: live-claim2
  namespace: avideo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
status: {}
